使用 try except 语句来捕获错误。
了解产生了什么异常往往很重要，所以 Python 允许你在处理异常时得到与之关联的数据。这有两种方法：可以使用 sys 模块的功能，也可以使用拓展的 try/except 语句。

标准库 sys 模块，提供了 exc_info 函数，会提供当前处理异常的有关信息。调用 exc_info 时，这个函数会返回一个包括 3 个值的元组，其中第一个值指示异常的类型，第二个值详细描述异常的值，第三个值包含一个回溯跟踪对象，允许访问回溯跟踪消息。如果当前没有异常，exc_info 会对各个元组值返回 Python 的 null 值，即：(None, None, None)

避免紧耦合的代码


阻塞
后面的代码要等前面的代码运行完才能工作。

对我们的网页APP来说，用户完全没有必要等待写入数据库的过程，而直接拿到结果。也就是说，用户点击 "Do it!" 之后，就应该产生两条分支，一条把结果返回给用户，另一条把内容写入数据库。
